function determinant = det_test_f(q)
%DET_TEST_F
%    DETERMINANT = DET_TEST_F(Q)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Jan-2023 16:42:46

t2 = cos(q);
determinant = t2.*(2.1e+1./3.2e+2)+t2.^2.*3.0546875e-2+9.0./2.56e+2;
