function determinant = det_test3_f(L,lz,m,off,q,q1)
%DET_TEST3_F
%    DETERMINANT = DET_TEST3_F(L,LZ,M,OFF,Q,Q1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    03-Apr-2024 11:32:05

determinant = L.^2.*lz.^4.*m.^4.*off.^2.*cos(q-q1).^2.*sin(q).^2.*4.0;
