function determinant = det_test2_f(q)
%DET_TEST2_F
%    DETERMINANT = DET_TEST2_F(Q)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    03-Apr-2024 11:32:00

determinant = sin(q).^2.*7.03125e-4+3.4453125e-2;
