function determinant = det_test0_f(L,ixx,lz,m,off,q2,q3)
%DET_TEST0_F
%    DETERMINANT = DET_TEST0_F(L,IXX,LZ,M,OFF,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    03-Apr-2024 11:31:50

t2 = lz.^2;
t3 = m.*t2;
determinant = (ixx+t3+lz.*m.*(L.*cos(q2)+off.*sin(q2))).^2+(ixx+t3+lz.*m.*(L.*cos(q3)-off.*sin(q3))).^2;
