function determinant = det_test1_f(L,ixx,lz,m,off,q)
%DET_TEST1_F
%    DETERMINANT = DET_TEST1_F(L,IXX,LZ,M,OFF,Q)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    03-Apr-2024 11:31:54

t2 = cos(q);
t3 = sin(q);
t4 = lz.^2;
t5 = L.*t2;
t6 = off.*t3;
t7 = m.*t4;
determinant = (ixx+t7+lz.*m.*(t5+t6)).^2+(ixx+t7+lz.*m.*(t5-t6)).^2;
