function B = B_planarX_arms_f(iA1yy,iA2yy,iCyy,lCz,mC,qAL1,qAL2,qAR1,qAR2)
%B_planarX_arms_f
%    B = B_planarX_arms_f(iA1yy,iA2yy,iCyy,lCz,mC,qAL1,qAL2,qAR1,qAR2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    23-May-2023 15:55:03

t2 = cos(qAL1);
t3 = cos(qAL2);
t4 = cos(qAR1);
t5 = cos(qAR2);
t6 = qAL1+qAL2;
t7 = qAR1+qAR2;
t8 = cos(t6);
t9 = cos(t7);
t10 = t2.*1.44054e+1;
t11 = t3.*1.64465e-1;
t12 = t3.*8.22325e-2;
t13 = t4.*2.471115e+1;
t15 = t5.*7.42035e-1;
t17 = t5.*3.710175e-1;
t14 = -t11;
t16 = -t12;
t18 = t8.*1.0643235;
t20 = t9.*4.8020265;
t22 = iA2yy+t17+3.03704325e-1;
t19 = -t18;
t21 = iA2yy+t16+1.4919325e-2;
t24 = t20+t22;
t26 = iA1yy+iA2yy+t13+t15+t20+3.419354325;
t23 = t19+t21;
t25 = iA1yy+iA2yy+t10+t14+t19+1.014819325;
B = reshape([iA1yy.*2.0+iA2yy.*2.0+iCyy+t2.*2.88108e+1+t4.*4.94223e+1-t8.*2.128647+t9.*9.604053+t14+t15+lCz.^2.*mC+4.2306053365e+2,t25,t23,t26,t24,t25,iA1yy+iA2yy+t14+1.014819325,t21,0.0,0.0,t23,t21,iA2yy+1.4919325e-2,0.0,0.0,t26,0.0,0.0,iA1yy+iA2yy+t15+3.419354325,t22,t24,0.0,0.0,t22,iA2yy+3.03704325e-1],[5,5]);
