function B = B_planarZ_arms_f(iCzz,qAL1,qAR1)
%B_planarZ_arms_f
%    B = B_planarZ_arms_f(iCzz,qAL1,qAR1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    23-May-2023 15:19:16

t2 = cos(qAL1);
t3 = cos(qAR1);
t4 = t2.*8.056266e-1;
t5 = t3.*8.056266e-1;
B = reshape([iCzz+sin(qAL1).^2.*2.125626198+sin(qAR1).^2.*2.125626198+8.4444e-1,t4,t5,t4,2.142626198,0.0,t5,0.0,2.142626198],[3,3]);
