function n = n_planarZ_arms_f(fsC,fvC,qAL1,qAL1d,qAR1,qAR1d,qCd)
%n_planarZ_arms_f
%    N = n_planarZ_arms_f(fsC,fvC,qAL1,qAL1d,qAR1,qAR1d,qCd)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    23-May-2023 15:19:16

t2 = sin(qAL1);
t3 = sin(qAR1);
t4 = qAL1.*2.0;
t5 = qAR1.*2.0;
t6 = qCd.^2;
t7 = sin(t4);
t8 = sin(t5);
mt1 = [fvC.*qCd-qAL1d.^2.*t2.*8.056266e-1-qAR1d.^2.*t3.*8.056266e-1+fsC.*sign(qCd)+qAL1d.*qCd.*t7.*2.125626198+qAR1d.*qCd.*t8.*2.125626198;qAL1d.*1.2e+1+t2.*4.1553372e+1+sign(qAL1d).*1.0e+1-t6.*t7.*1.062813099];
mt2 = [qAR1d.*1.2e+1+t3.*4.1553372e+1+sign(qAR1d).*1.0e+1-t6.*t8.*1.062813099];
n = [mt1;mt2];
