function n = n_planarX_arms_f(fsC,fvC,lCz,mC,qAL1,qAL2,qAL1d,qAL2d,qAR1,qAR2,qAR1d,qAR2d,qC,qCd)
%n_planarX_arms_f
%    N = n_planarX_arms_f(fsC,fvC,lCz,mC,qAL1,qAL2,qAL1d,qAL2d,qAR1,qAR2,qAR1d,qAR2d,qC,qCd)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    23-May-2023 15:55:03

t2 = sin(qAL1);
t3 = sin(qAL2);
t4 = sin(qAR1);
t5 = sin(qAR2);
t6 = sin(qC);
t7 = qAL1+qAL2;
t8 = qAR1+qAR2;
t9 = qAL1+qC;
t10 = qAR1+qC;
t11 = qAL1d.^2;
t12 = qAL2d.^2;
t13 = qAR1d.^2;
t14 = qAR2d.^2;
t15 = qCd.^2;
t16 = qC+t7;
t17 = qC+t8;
t18 = sin(t7);
t19 = sin(t8);
t20 = sin(t9);
t21 = sin(t10);
t26 = qAL1d.*qAL2d.*t3.*1.64465e-1;
t27 = qAL2d.*qCd.*t3.*1.64465e-1;
t28 = t3.*t12.*8.22325e-2;
t29 = qAR1d.*qAR2d.*t5.*7.42035e-1;
t30 = qAR2d.*qCd.*t5.*7.42035e-1;
t31 = t5.*t14.*3.710175e-1;
t22 = sin(t16);
t23 = sin(t17);
t24 = t20.*3.1164e+1;
t25 = t21.*5.3459e+1;
t32 = -t29;
t33 = -t30;
t35 = -t31;
t38 = t15.*t18.*1.0643235;
t40 = t15.*t19.*4.8020265;
t34 = t22.*2.30251;
t37 = t23.*1.038849e+1;
t39 = -t38;
t36 = -t34;
et1 = t6.*9.056376e+2+t24+t25+t26+t27+t28+t32+t33+t35+t36+t37+fvC.*qCd-t2.*t11.*1.44054e+1-t4.*t13.*2.471115e+1+t11.*t18.*1.0643235+t12.*t18.*1.0643235-t13.*t19.*4.8020265-t14.*t19.*4.8020265+fsC.*sign(qCd)+lCz.*mC.*t6.*(4.9e+1./5.0)+qAL1d.*qAL2d.*t18.*2.128647-qAR1d.*qAR2d.*t19.*9.604053;
et2 = qAL1d.*qCd.*t2.*(-2.88108e+1)+qAL1d.*qCd.*t18.*2.128647+qAL2d.*qCd.*t18.*2.128647-qAR1d.*qCd.*t4.*4.94223e+1-qAR1d.*qCd.*t19.*9.604053-qAR2d.*qCd.*t19.*9.604053;
n = [et1+et2;qAL1d.*1.2e+1+t24+t26+t27+t28+t36+t39+sign(qAL1d).*1.0e+1+t2.*t15.*1.44054e+1;qAL2d.*(9.0./2.0)+t36+t39+sign(qAL2d).*(9.0./2.0)-t3.*t11.*8.22325e-2-t3.*t15.*8.22325e-2-qAL1d.*qCd.*t3.*1.64465e-1;qAR1d.*1.2e+1+t25+t32+t33+t35+t37+t40+sign(qAR1d).*1.0e+1+t4.*t15.*2.471115e+1;qAR2d.*(9.0./2.0)+t37+t40+sign(qAR2d).*(9.0./2.0)+t5.*t13.*3.710175e-1+t5.*t15.*3.710175e-1+qAR1d.*qCd.*t5.*7.42035e-1];
