function B = B_planar_f(lCz,mC,qAL,qAR)
%B_planar_f
%    B = B_planar_f(lCz,mC,qAL,qAR)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    19-Apr-2023 14:33:05

t2 = cos(qAL);
t3 = cos(qAR);
t4 = sin(qAL);
t5 = sin(qAR);
t6 = t4.*8.066298e-1;
t7 = t5.*8.066298e-1;
t9 = t2.*1.92317526e+1;
t10 = t3.*1.92317526e+1;
t8 = -t7;
t11 = t6+t9+1.041826068;
t12 = t8+t10+1.041826068;
B = reshape([t2.*3.84635052e+1+t3.*3.84635052e+1+t4.*1.6132596-t5.*1.6132596+lCz.^2.*mC+7.13355852136e+2,t11,t12,t11,1.041826068,0.0,t12,0.0,1.041826068],[3,3]);
