function n = n_planar_f(fsC,fvC,lCz,mC,qAL,qALd,qAR,qARd,qC,qCd)
%N_PLANAR_F
%    N = N_PLANAR_F(fsC,fvC,lCz,mC,qAL,qALd,qAR,qARd,qC,qCd)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    19-Apr-2023 14:33:05

t2 = cos(qAL);
t3 = cos(qAR);
t4 = sin(qAL);
t5 = sin(qAR);
t6 = sin(qC);
t7 = qAL+qC;
t8 = qAR+qC;
t9 = qALd.^2;
t10 = qARd.^2;
t11 = qCd.^2;
t12 = sin(t7);
t13 = sin(t8);
t14 = t12.*4.1605116e+1;
t15 = t13.*4.1605116e+1;
mt1 = [t6.*1.5360324e+3+t14+t15+fvC.*qCd+t2.*t9.*8.066298e-1-t3.*t10.*8.066298e-1-t4.*t9.*1.92317526e+1-t5.*t10.*1.92317526e+1+fsC.*sign(qCd)+lCz.*mC.*t6.*(4.9e+1./5.0)+qALd.*qCd.*t2.*1.6132596-qALd.*qCd.*t4.*3.84635052e+1-qARd.*qCd.*t3.*1.6132596-qARd.*qCd.*t5.*3.84635052e+1];
mt2 = [qALd.*1.5e+1+t14+sign(qALd).*1.1e+1-t2.*t11.*8.066298e-1+t4.*t11.*1.92317526e+1;qARd.*1.5e+1+t15+sign(qARd).*1.1e+1+t3.*t11.*8.066298e-1+t5.*t11.*1.92317526e+1];
n = [mt1;mt2];
